Repository emotion-js/emotion, pull requests merged in 2018-06, with the labels that each got.

#691 Fix example in TS docs
  docs/typescript.md
Labels: merge me!

#694 Add react/preact as peer-dependencies to react-emotion/preact-emotion
  packages/create-emotion-styled/package.json
  packages/emotion-theming/package.json
  packages/preact-emotion/package.json
  packages/react-emotion/package.json
  packages/react-emotion/types/index.d.ts
  yarn.lock
Labels: merge me!

#678 Fix react-emotion typing
  packages/react-emotion/types/index.d.ts
  packages/react-emotion/types/tests.tsx
  packages/react-emotion/types/tsconfig.json
Labels: Tag: Enhancement

#679 Update typescript document to match with current types
  docs/typescript.md
  packages/site/src/utils/highlight-css.js
Labels: Tag: Documentation

#704 Update rollup to fix bundle size regression
  package.json
  packages/create-emotion-styled/package.json
  packages/create-emotion/package.json
  packages/emotion-theming/package.json
  packages/emotion/package.json
  packages/preact-emotion/package.json
  packages/react-emotion/package.json
  rollup.config.js
  yarn.lock
Labels: Tag: Bug Fix

#709 Fix serializer replacing non emotion class names
  packages/jest-emotion/src/replace-class-names.js
  packages/jest-emotion/test/__snapshots__/printer.test.js.snap
  packages/jest-emotion/test/printer.test.js
Labels: Tag: Bug Fix

#710 Remove allowSyntheticDefaultImports from typings
  packages/create-emotion-styled/types/index.d.ts
  packages/create-emotion-styled/types/react.d.ts
  packages/create-emotion-styled/types/test.tsx
  packages/create-emotion-styled/types/tsconfig.json
  packages/emotion-server/types/tests.tsx
  packages/emotion-server/types/tsconfig.json
  packages/emotion-theming/types/tests.tsx
  packages/emotion-theming/types/tsconfig.json
  packages/emotion/types/tests.tsx
  packages/emotion/types/tsconfig.json
  packages/preact-emotion/types/test.tsx
  packages/preact-emotion/types/tsconfig.json
  packages/react-emotion/types/tests.tsx
  packages/react-emotion/types/tsconfig.json
Labels: Tag: Bug Fix, TypeScript

#714 Fix tsconfig for emotion-theming
  packages/emotion-theming/types/tsconfig.json
Labels: Tag: Internal, TypeScript

#723 Add typings for jest-emotion
  packages/jest-emotion/package.json
  packages/jest-emotion/types/index.d.ts
  packages/jest-emotion/types/test.ts
  packages/jest-emotion/types/tsconfig.json
  packages/jest-emotion/types/tslint.json
  yarn.lock
Labels: Tag: Enhancement, TypeScript

#730 No duplicated ast nodes
  package.json
  packages/babel-plugin-emotion/package.json
  packages/babel-plugin-emotion/src/babel-utils.js
  packages/babel-plugin-emotion/test/__snapshots__/css-prop.test.js.snap
  packages/babel-plugin-emotion/test/__snapshots__/macro.test.js.snap
  packages/babel-plugin-emotion/test/macro.test.js
  packages/babel-plugin-emotion/test/util.js
  yarn.lock
Labels: Tag: Bug Fix

#731 Fix jest-emotion for preact
  packages/jest-emotion/package.json
  packages/jest-emotion/src/utils.js
  packages/jest-emotion/test/__snapshots__/preact.test.js.snap
  packages/jest-emotion/test/preact.test.js
  yarn.lock
Labels: Tag: Bug Fix

#741 Improve labels and upgrade @emotion/stylis
  .flowconfig
  packages/babel-plugin-emotion/package.json
  packages/babel-plugin-emotion/src/babel-utils.js
  packages/babel-plugin-emotion/test/__snapshots__/css-prop.test.js.snap
  packages/babel-plugin-emotion/test/__snapshots__/css.test.js.snap
  packages/babel-plugin-emotion/test/css.test.js
  packages/babel-plugin-emotion/test/util.js
  packages/create-emotion/package.json
  test/empty.js
  yarn.lock
Labels: Tag: Enhancement

#720 Use emotion-next in the site, update to gatsby v2 and add Community page
  .flowconfig
  package.json
  packages/babel-plugin-emotion/src/babel-utils.js
  packages/babel-plugin-emotion/src/index.js
  packages/emotion-theming/src/theme-provider.js
  packages/emotion/test/insertion.test.js
  packages/jest-emotion/src/utils.js
  packages/site/.babelrc
  packages/site/.eslintrc.js
  packages/site/gatsby-config.js
  packages/site/gatsby-node.js
  packages/site/gatsby-ssr.js
  packages/site/package.json
  packages/site/plugins/gatsby-plugin-emotion-next-compat/gatsby-browser.js
  packages/site/plugins/gatsby-plugin-emotion-next-compat/gatsby-node.js
  packages/site/plugins/gatsby-plugin-emotion-next-compat/gatsby-ssr.js
  packages/site/plugins/gatsby-plugin-emotion-next-compat/package.json
  packages/site/plugins/gatsby-plugin-favicon-fork/gatsby-node.js
  packages/site/plugins/gatsby-plugin-favicon-fork/gatsby-ssr.js
  packages/site/plugins/gatsby-plugin-favicon-fork/package.json
  packages/site/plugins/gatsby-remark-change-awesome/index.js
  packages/site/plugins/gatsby-remark-change-awesome/package.json
  packages/site/plugins/gatsby-remark-live-code/index.js
  packages/site/plugins/gatsby-remark-live-code/package.json
  packages/site/plugins/gatsby-remark-remove-readme-titles/index.js
  packages/site/plugins/gatsby-remark-remove-readme-titles/package.json
  packages/site/src/components/Box.js
  packages/site/src/components/DocMetadata.js
  packages/site/src/components/DocWrapper.js
  packages/site/src/components/Link.js
  packages/site/src/components/Playground.js
  packages/site/src/components/RenderHAST.js
  packages/site/src/components/Title.js
  packages/site/src/components/live/compile.js
  packages/site/src/components/live/compiler.js
  packages/site/src/components/live/worker.js
  packages/site/src/html.js
  packages/site/src/layouts/index.js
  packages/site/src/pages/404.js
  packages/site/src/pages/community.js
  packages/site/src/pages/docs.js
  packages/site/src/pages/index.js
  packages/site/src/templates/doc.js
  packages/site/src/utils/algolia-styles.js
  packages/site/src/utils/demo-buttons.js
  packages/site/src/utils/global.js
  packages/site/src/utils/make-prism-manual.js
  packages/site/src/utils/markdown-styles.js
  packages/site/src/utils/style.js
  packages/site/transform.js
  yarn.lock
Labels: Tag: Documentation

#636 Add eslint-plugin-emotion to docs
  docs/docs.yaml
Labels: Tag: Documentation, merge me!
