Repository emotion-js/emotion, pull requests merged in 2018-10, with the labels that each got.

#890 Add nohoist option not to hoist dtslint
  package.json
Labels: TypeScript

#897 Readd test:typescript check
  .circleci/config.yml
  packages/create-emotion-server/package.json
  packages/emotion-server/package.json
  packages/emotion-server/types/tests.tsx
  yarn.lock
Labels: Tag: Internal, TypeScript

#907 Add typings of @emotion/is-prop-valid package
  packages/is-prop-valid/package.json
  packages/is-prop-valid/types/index.d.ts
  packages/is-prop-valid/types/tests.ts
  packages/is-prop-valid/types/tsconfig.json
  packages/is-prop-valid/types/tslint.json
Labels: TypeScript

#908 Fix typings of @emotion/styled-base to work well with ref
  packages/styled-base/types/helper.d.ts
  packages/styled-base/types/index.d.ts
  packages/styled-base/types/tests.tsx
Labels: Tag: Bug Fix, TypeScript

#912 Fix typings of old packages
  packages/create-emotion-server/types/index.d.ts
  packages/create-emotion-server/types/tests.tsx
  packages/create-emotion-server/types/tslint.json
  packages/create-emotion/package.json
  packages/create-emotion/types/index.d.ts
  packages/create-emotion/types/tests.tsx
  packages/create-emotion/types/tslint.json
  packages/emotion-server/types/index.d.ts
  packages/emotion-server/types/tests.tsx
  packages/emotion-server/types/tslint.json
  packages/emotion-theming/package.json
  packages/emotion-theming/types/helper.d.ts
  packages/emotion-theming/types/index.d.ts
  packages/emotion-theming/types/tests.tsx
  packages/emotion-theming/types/tslint.json
  packages/emotion/package.json
  packages/emotion/types/index.d.ts
  packages/emotion/types/tests.tsx
  packages/emotion/types/tslint.json
  packages/react-emotion/package.json
  packages/react-emotion/types/index.d.ts
  packages/react-emotion/types/tests.tsx
  packages/react-emotion/types/tslint.json
  yarn.lock
Labels: Tag: Bug Fix, TypeScript

#924 Fix typings of jest-emotion package
  packages/jest-emotion/types/index.d.ts
  packages/jest-emotion/types/test.ts
  packages/jest-emotion/types/tslint.json
Labels: Tag: Bug Fix, TypeScript

#923 Support innerRef in v10
  packages/styled-base/src/index.js
  packages/styled/__tests__/styled-dom.js
  scripts/test-utils/src/index.js
Labels: Tag: Enhancement

#936 Add missing files in package.json
  packages/styled/package.json
Labels: Tag: Bug Fix, TypeScript

#937 Refine exports from TS definitions
  packages/core/types/index.d.ts
  packages/create-emotion/types/index.d.ts
  packages/css/types/index.d.ts
  packages/emotion/types/index.d.ts
  packages/styled-base/types/index.d.ts
  packages/styled/types/index.d.ts
Labels: TypeScript

#935 Add Compare website link to README
  README.md
Labels: Tag: Documentation

#926 Give packages stricter dependencies
  package.json
  packages/babel-plugin-emotion/package.json
  packages/cache/package.json
  packages/core/package.json
  packages/create-emotion-server/package.json
  packages/create-emotion-server/types/index.d.ts
  packages/create-emotion-server/types/tests.tsx
  packages/create-emotion/package.json
  packages/create-emotion/types/tests.ts
  packages/emotion-server/package.json
  packages/emotion-theming/package.json
  packages/emotion/package.json
  packages/emotion/types/tests.ts
  packages/jest-emotion/package.json
  packages/native/package.json
  packages/primitives/package.json
  packages/react-emotion/package.json
  packages/serialize/package.json
  yarn.lock
Labels: Tag: Bug Fix

#946 Fix labels of size badges in README
  README.md
Labels: documentation

#957 Fix @emotion/serialize typing to work without strictNullChecks
  packages/serialize/types/helper.d.ts
  packages/serialize/types/index.d.ts
  yarn.lock
Labels: TypeScript
