Repository emotion-js/emotion, pull requests merged in 2018-04, with the labels that each got.

#609 Allow labels to be composed
  packages/create-emotion/src/index.js
  packages/emotion-server/test/auto-label/__snapshots__/auto-label.test.js.snap
  packages/emotion/test/auto-label/auto-label.test.js
  packages/react-emotion/test/auto-label/__snapshots__/auto-label.test.js.snap
  packages/react-emotion/types/index.d.ts
Labels: Tag: Enhancement, merge me!

#612 Use @emotion/is-prop-valid for checking valid props on string tags
  packages/create-emotion-styled/package.json
  packages/create-emotion-styled/src/props.js
  packages/create-emotion-styled/src/utils.js
  yarn.lock
Labels: Tag: Internal

#616 Support shouldForwardProp in styled's options
  packages/create-emotion-styled/src/index.js
  packages/create-emotion-styled/src/utils.js
  packages/react-emotion/test/__snapshots__/index.test.js.snap
  packages/react-emotion/test/index.test.js
Labels: Tag: Enhancement

#628 Remove emotion-utils and use packages from emotion-js/next
  .flowconfig
  packages/babel-plugin-emotion/package.json
  packages/babel-plugin-emotion/src/index.js
  packages/create-emotion-server/package.json
  packages/create-emotion-styled/package.json
  packages/create-emotion-styled/src/index.js
  packages/create-emotion/package.json
  packages/create-emotion/src/index.js
  packages/create-emotion/src/utils.js
  packages/emotion-utils/package.json
  packages/emotion-utils/src/hash.js
  packages/emotion-utils/src/index.js
  packages/emotion-utils/src/stylis.js
  packages/emotion/test/__snapshots__/insertion.test.js.snap
  packages/emotion/test/insertion.test.js
  packages/site/package.json
  yarn.lock
Labels: Tag: Internal, merge me!

#622 Add support to jest-emotion for printing DOM Elements (#619)
  packages/jest-emotion/README.md
  packages/jest-emotion/package.json
  packages/jest-emotion/src/index.js
  packages/jest-emotion/test/__snapshots__/printer.test.js.snap
  packages/jest-emotion/test/printer.test.js
  yarn.lock
Labels: Tag: Enhancement

#633 Add warning for invalid content values in objects
  packages/create-emotion/src/utils.js
  packages/emotion/test/__snapshots__/warnings.test.js.snap
  packages/emotion/test/warnings.test.js
Labels: Tag: Enhancement, merge me!
